### ISSUE TITLE
[User Story] Infrastructure build - Azure environment

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#103]
Added to Sprint 2 (milestone) during 9/17/18 Sprint planning meeting.

Issue |Infrastructure build - Azure environment
----------|----------
User Story | #224
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5 (S2) + 3 points (S3)

**Comment by agoldingay** [comment]
Per Michael, Chris working on obtaining access to the Azure CC subscription

**Comment by mtn217** [comment]
Removing `Risk: Virtual CPU limit on Azure subscription. Remediation needed.` from the description because we successfully able to spin up a second ACC VM (which was our initial goal) that utilizes two Virtual CPUs.

**Comment by mtn217** [comment]
Non-SGX version of NEXT is currently hosted on Azure VM and live at:
http://40.114.84.55:4200/

The VM is currently using a modified version of the master branch that utilizes the IP 40.114.84.55 instead of localhost. The modified version can be seen in my forked NEXT repo on the support-azure-vm branch (https://github.com/mtn217/sawtooth-next-directory/tree/support-azure-vm). Test data has also been populated from the file `bin/populate_test_data.py`

I will be working on making a configuration to allow developers to run NEXT in prod.

**Comment by mtn217** [comment]
PR #146 was created because as we start to run NEXT onto different environments (dev, prod, etc.), we needed to easily adapt the code for each environment.

Now, I am working on setting up a CI/CD pipeline to easily update the NEXT platform code that is currently being hosted on Azure.

**Comment by codingalyona** [comment]
additional 3 points. - sprint 3

**Comment by mtn217** [comment]
Travis integrated in PR#173 for CI/CD pipeline for one node. Now the next task is to set up the code base to perform CI/CD for multi nodes and have them talk to each other through sawtooth blockchain network.

**Comment by PatrickLammers** [comment]
closing this one here...  will revisit Azure environment in V2.0 as it nears
