### ISSUE TITLE
empty users in the list

### ISSUE THREAD

**Issue by PatrickLammers** [hyperledger/sawtooth-next-directory#1277]
User Story | 'U' users showing in the list
----------|----------
T-shirt size:  | 
User Story | "As a PO of Next, I want the list of users to show correctly so I'm not embarrassed by my app during demos."
Description | LDAP query is catching empty users and ADM users...  why? 
Acceptance Criteria/Tests | show the list of people in the no-org view, make sure there are no empty entries or ADM OU showing in the list.

**Comment by PatrickLammers** [comment]
related to #1100 maybe?

**Comment by mtn217** [comment]
No code is needed for this ticket. Our prod parallel test AD instance has been cleaned up to remove any users with no display name field. Also, the scope of the USER_BASE_DN has been limited to not show our service accounts anymore (the ADM_ accounts). Previously on our demo and our staging environment I passed in the USER_BASE_DN to get all users within our prod parallel test AD. 

Also this does not relate to #1100 because that was when NEXT was trying to look up users that have not been imported. Names were not showing up here because the AD user did not have a value set in their display name.
