### ISSUE TITLE
Enforce Username unique-ness

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#1331]
[User Story] | Enforce username unique-ness
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | S
User Story | "As a developer I do not want peopl to be able to create users that already exist."
Description | Currently is you create a user with a username that matches someone else, it will set that accounts password to whatever you use and then also allow you access to the  account's information.  We need to prevent this from happening.  The signup field using username should be unique.  The files affected are server/api/users and server/api/authentication
Acceptance Criteria/Tests | Tests for uniqueness enforcement.  Be able to login to LDAP.  Be able to create a user.  Be unable to create a user that has the same user as an ldap person.  Be unable to access ldap users stuff through a local user.

**Comment by Srinuthalapati** [comment]
**Patrick's Description**: Currently with the ability to log in with either NEXT creds or corporate AD creds, it seems that I can create a NExt acct that matches my AD acct and get all the privileges tied to my AD creds. While removing the UI switch to allow me to pick NEXT/AD will hide this issue, we really should be more robust about rejecting this on login.

**Comment by Srinuthalapati** [comment]
**Patrick's Acceptance-Criteria** from **#1109**: May be tricky to demo this one after we disable radio button on login page -- need to show that a next acct with a different PW than my AD acct doesn't get my AD level of access.

**Comment by Srinuthalapati** [comment]
Steps to be taken:

1. Identify the POST API that is being called when Login button is hit. This API will get the new user account creation details including - "username"
2. Also, identify the GET API that is called to fetch the list of all users from the Rethink Database.
3. Identify a place where sounds logical to be implemented when POST API details are submitted to the corresponding table in database. Because, this is where we shall restrict that new data from being added if the username is NOT UNIQUE.
4. Introduce the error handling there to display - "user already exists" message.
5. Write the test case around this logic, if necessary.
6. Test this modified functionality.
7. If working fine, peer review & make a pull request.

**Comment by Srinuthalapati** [comment]
![Final Result](https://user-images.githubusercontent.com/23491817/54470077-4c5ae000-475f-11e9-8481-ea30454ca23c.JPG)

**Comment by Srinuthalapati** [comment]
![Final Success Result](https://user-images.githubusercontent.com/23491817/54470910-88953d00-476d-11e9-920c-0b4aa5993d1b.JPG)
