### ISSUE TITLE
S4+ [Task] [Bug] Generated protobufs are not found at runtime while running in non-dev mode

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#291]
Title | Generated protobufs are not found at runtime
----------|----------
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 2
Applications or Systems impacted | Application startup
Description | Upon clean checkout of master: Doing a 'bin/build -p' followed by a 'bin/start' yields error: No module named 'rbac.transaction_creation.protobuf'

**Comment by nadiabahrami** [comment]
This does not appear to be fixed yet.  Repro steps:
With the latest pull from upstream:
1. run ./bin/build -p
2. run ./bin/start

Result: Lots of errors.  I have attached terminal pictures to show
![Screen Shot 2018-10-24 at 9.07.32 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/b96396f3-0cf8-4fe9-82b3-775905ad41da)
![Screen Shot 2018-10-24 at 9.07.24 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/cff92434-b2a0-4fa9-94e4-b140a4f52f4a)
![Screen Shot 2018-10-24 at 9.07.16 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/8eef9d50-fb7a-429f-80d1-5c659a9d16b5)
![Screen Shot 2018-10-24 at 9.07.01 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/b0ec7980-1f73-437e-98c9-970ae6558271)

**Comment by nadiabahrami** [comment]
Someone else please try and confirm whether this is still an issue or fixed.

**Comment by jbobo** [comment]
I checked both methods. I get protobuf issues using the steps @nadiabahrami gave, the solution @adamgering also resolves the issues. If we have to build every time, maybe we should make this the default instead of requiring a flag. At the worst it could work as a hotfix?
[nadia-bug.txt](https://github.com/hyperledger/sawtooth-next-directory/files/2512023/nadia-bug.txt)

**Comment by adamgering** [comment]
You don't need to build everytime, only when files change outside of the DockerFile, in order to pull in changes. The DockerFile does a file copy.

Thus, really, no one should use this without the dev flag; and perhaps we should make that the only option. That requires people enable volume mounts, but for the purpose of all other users, grabbing the YAML that pulls docker images will be the correct method, once builds have stabilized (we can do weekly or bi-weekly builds of the docker images).

**Comment by adamgering** [comment]
Sometimes rebuilds do not work. Not sure why, clearing the docker images seems to fix the problem.

**Comment by jbobo** [comment]
But is there any downside to rebuilding any time? it's not making an appreciate difference in startup time. Exiting with just `Ctrl + c` always gives me errors on the next build, but running `docker-compose down` or `docker system prune` after taking down the images works consistently.

**Comment by adamgering** [comment]
```bin/stop``` or ```docker-compose down``` must be done everytime you stop the app.

**Comment by jbobo** [comment]
I've never had issues with starting up docker after running either command
