### ISSUE TITLE
Expiration: Add Requester/Requested_by fields to Proposal

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#824]
For proposal expiration: Include information about
  requester:
    - job title 
    - name
    - email

**Comment by PatrickLammers** [comment]
I *think* you are proposing adding this information so that an approver will be able to see information on someone who is asking for re-auth (expiring permissions)...

Don't we already have this information available for new requests?  I don't see why we would need this only for Expiration?  As I understand the current workflow, when my permissions are about to expire I get an alert (email and an alert icon in the UI) so I go to the proper role page and press the "request Extension" button (UI is TBD) 

Then the role owner and my manager each get a request to approve.... they can see my details by going to the People page (or on the email that gets generated, right?)  Let's chat...

**Comment by PatrickLammers** [comment]
This seems like a task in support of functionality we already have.  Closing.
